export interface updateemployee {
    "id":number,
    "empId": string,
    "empName": string,
    "password": string,
    "mobileNumber":number,
    "role": string,
    "designation": string,
    "dob":string,
    "doj":string,
    "department": string,
    "panNo": string, 
    "adharNo": string,
    "status": string,
    "bloodGroup":string,
    "city":string,
    "state":string,
    "pincode":number,
    "country":string,
    "email":string
}